export const CREATE_CENTER_REQUEST = "CREATE_CENTER_REQUEST";
export const CREATE_CENTER_SUCCESS = "CREATE_CENTER_SUCCESS";
export const CREATE_CENTER_RESET = " CREATE_CENTER_RESET";
export const CREATE_CENTER_FAIL = "CREATE_CENTER_FAIL";

export const ALL_CENTERS_REQUEST = "ALL_CENTERS_REQUEST";
export const ALL_CENTERS_SUCCESS = "ALL_CENTERS_SUCCESS";
export const ALL_CENTERS_FAIL = "ALL_CENTERS_FAIL";

export const UPDATE_CENTER_REQUEST = "UPDATE_CENTER_REQUEST";
export const UPDATE_CENTER_SUCCESS = "UPDATE_CENTER_SUCCESS";
export const UPDATE_CENTER_RESET = "UPDATE_CENTER_RESET";
export const UPDATE_CENTER_FAIL = "UPDATE_CENTER_FAIL";

export const DELETE_CENTER_REQUEST = "DELETE_CENTER_REQUEST";
export const DELETE_CENTER_SUCCESS = "DELETE_CENTER_SUCCESS";
export const DELETE_CENTER_RESET = "DELETE_CENTER_RESET";
export const DELETE_CENTER_FAIL = "DELETE_CENTER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
