export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_RESET = " CREATE_CLASS_RESET";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";

export const MY_CLASS_REQUEST = "MY_CLASS_REQUEST";
export const MY_CLASS_SUCCESS = "MY_CLASS_SUCCESS";
export const MY_CLASS_FAIL = "MY_CLASS_FAIL";

export const ALL_CLASS_REQUEST = "ALL_CLASS_REQUEST";
export const ALL_CLASS_SUCCESS = "ALL_CLASS_SUCCESS";
export const ALL_CLASS_FAIL = "ALL_CLASS_FAIL";

export const UPDATE_CLASS_REQUEST = "UPDATE_CLASS_REQUEST";
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_RESET = "UPDATE_CLASS_RESET";
export const UPDATE_CLASS_FAIL = "UPDATE_CLASS_FAIL";

export const DELETE_CLASS_REQUEST = "DELETE_CLASS_REQUEST";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_RESET = "DELETE_CLASS_RESET";
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL";

export const CLASS_DETAILS_REQUEST = "CLASS_DETAILS_REQUEST";
export const CLASS_DETAILS_SUCCESS = "CLASS_DETAILS_SUCCESS";
export const CLASS_DETAILS_FAIL = "CLASS_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
